CREATE DATABASE IF NOT EXISTS webHorario;
USE webHorario;

CREATE TABLE turnos(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE horarios(
	id INT NOT NULL AUTO_INCREMENT,
	inicio TIME NOT NULL,
	fim TIME NOT NULL,
	CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE turnos_horarios(
	turno_id INT NOT NULL,
	horario_id INT NOT NULL,
	CONSTRAINT PRIMARY KEY(turno_id, horario_id),
	CONSTRAINT FOREIGN KEY(turno_id)
	REFERENCES turnos(id),
	CONSTRAINT FOREIGN KEY(horario_id)
	REFERENCES horarios(id)
);

CREATE TABLE cursos(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	iniciais CHAR(5) NOT NULL,
	turno_id INT NOT NULL,
	CONSTRAINT PRIMARY KEY(id),
	CONSTRAINT FOREIGN KEY(turno_id)
	REFERENCES turnos(id)
);

CREATE TABLE disciplinas(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	iniciais CHAR(4) NOT NULL,
	cargaHoraria INT NOT NULL,
	CONSTRAINT PRIMARY KEY(id)
);

CREATE TABLE cursos_disciplinas(
	curso_id INT NOT NULL,
	disciplina_id INT NOT NULL,
	CONSTRAINT PRIMARY KEY(curso_id, disciplina_id),
	CONSTRAINT FOREIGN KEY(curso_id)
	REFERENCES cursos(id),
	CONSTRAINT FOREIGN KEY(disciplina_id)
	REFERENCES disciplinas(id)
);
